 Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [1]:
import numpy as np 

In [4]:
array1 = np.array([1, 2, 3.4, 4.9, 5],dtype=int)
array1

array([1, 2, 3, 4, 5])

In [5]:
#eleman sayısı
array1.size

5

In [6]:
#boyut
array1.ndim

1

 İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [8]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [10]:
array2.size

10

In [11]:
array2.ndim

2

In [18]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
array2.shape

(2, 5)

In [64]:
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [65]:
array3.size

12

In [66]:
array3.ndim

3

In [67]:
print(array3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [68]:
array3.shape

(1, 4, 3)

 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 

In [69]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [70]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
array2 [0,3]

4

In [75]:
array3 [0,1,2]

6

In [82]:
array2 [1,:2]

array([6, 7])

In [83]:
array3 [0,2,:3]

array([7, 8, 9])

In [84]:
array3[0, :, 1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [87]:
#concatenate: dizileri belirli bir eksende birleştiren fonksiyondur
#axis=0: Satırlar boyunca birleştirir (dikey).
#axis=1: Sütunlar boyunca birleştirir (yatay).
arr1=([[0,0,0],[0,0,0]])
arr2=([[1,1,1],[1,1,1]])

print(np.concatenate([arr1,arr2]))

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [88]:
print(np.concatenate([arr1,arr2], axis=1))

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
